<?php
/**
 * AjaxController.php
 *
 * @package app\controllers
 * @date: 06.11.2015 21:24
 * @author: Kyshnerev Dmitriy <dimkysh@mail.ru>
 */

namespace app\controllers;


use yii\web\Controller;

/**
 * Class AjaxController
 * @package app\controllers
 */
class AjaxController extends Controller
{
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        $response = \Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        parent::init(); // TODO: Change the autogenerated stub
    }

}