<?php
/**
 * ProfilerTest.php
 *
 * @package tests\codeception\unit\models\amop\models
 * @date: 01.10.2015 20:46
 * @author: Kyshnerev Dmitriy <dimkysh@mail.ru>
 */

namespace tests\codeception\unit\models\amop\models;


use app\models\amop\models\Profiler;
use Codeception\Specify;
use tests\codeception\unit\DbTestCase;

/**
 * Class ProfilerTest
 * @package tests\codeception\unit\models\amop\models
 */
class ProfilerTest extends DbTestCase
{
    use Specify;

    /**
     * @Override
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub
    }

    /**
     * @Override
     */
    protected function _after()
    {
        parent::_after(); // TODO: Change the autogenerated stub
    }


    /**
     * Тест методов валидации
     */
    public function testValidate() {
        $model = new Profiler();
        $this->specify('validate type', function() use ($model){
            $model->type = 1666;
            $model->validate();

            $this->assertContains('Type message not found', $model->getErrors('type'));
        });
    }

}